[package]
name = "olist-cdn-preheat"
version = "0.1.0"
description = "OpenList CDN Preheat Desktop App"
authors = [ "jiwangyihao" ]
license = "MPL-2.0"
repository = "https://github.com/jiwangyihao/olist-cdn-preheat"
edition = "2021"

[lib]
name = "olist_cdn_preheat_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies.tauri-build]
version = "2.5"
features = [ ]

[dependencies]
tauri-plugin-shell = "2.3"
tauri-plugin-notification = "2.3"
tauri-plugin-os = "2.3"
tauri-plugin-fs = "2.4"
tauri-plugin-store = "2.4"
serde_json = "1"

[dependencies.tauri]
version = "2.9"
features = [
  "tray-icon",
  "unstable"
]

[dependencies.serde]
version = "1"
features = [ "derive" ]
